Description: Create an EC2 instance by AWS CloudFormation
Parameters:
    InstanceType:
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - m1.small
        - m1.large
      Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    KeyName:
    Type: String
    Default: aws-tasks
    Description: key pare value 
Resources:
  SecurityGroupHomeTaskTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: server_task_0
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
        Description: For traffic from Internet
      GroupDescription: Security Group for demo server
      VpcId: vpc-010e9f192a9bb2655
  EC2InstanceHomeTask:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2b
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: 'true'
          VolumeSize: '8'
          VolumeType: gp2
      ImageId: ami-013a129d325529d4d
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
      NetworkInterfaces:
      - Description: Primary network interface
        DeviceIndex: 0
        SubnetId: subnet-011b21a8898034b7c
        PrivateIpAddress: 172.31.32.4
      SecurityGroupIds:
        - Ref: SecurityGroupHomeTaskTraffic
Outputs:
  PublicIp:
    Description: Server Public IP
    Value: !GetAtt EC2InstanceHomeTask.PublicIp
    Export:
      Name: !Sub "${AWS::StackName}-PublicIp"
